name: Deploy Backend

on:
  push:
    branches:
      - master
      - main
    paths:
      - "backend/**"
  workflow_dispatch: # Allows manual trigger from the Actions tab

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          port: ${{ secrets.SERVER_PORT }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          script: |
            echo "Moving to project directory..."
            cd /srv/ismail_data/auto_apply_linkedin

            echo "Pulling latest changes..."
            git pull origin master

            echo "Installing backend dependencies..."
            cd backend
            npm i

            echo "Restarting PM2 process..."
            pm2 restart auto_apply_linkedin_backend --update-env
